#!/bin/sh

DIR='./'
count=`git rev-list HEAD | wc -l | sed -e 's/ *//g' | xargs -n1 printf %04d`
commit=`git show --abbrev-commit HEAD | grep '^commit' | sed -e 's/commit //'`
buildno="{\"version\": \"0.$count.$commit\"}"
echo version tag: \"0.$count.$commit\"
echo $buildno > "${DIR}/version.json"
