version: "3.3"

services:

  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "nginx-conf:/etc/nginx/conf.d"
      - "nginx-vhost:/etc/nginx/vhost.d"
      - "nginx-html:/usr/share/nginx/html"
      - "nginx-certs:/etc/nginx/certs:ro"
      - "/home/${MUD_HOST_USER}/config/proxy.conf:/etc/nginx/proxy.conf"

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "nginx-conf:/etc/nginx/conf.d"
      - "nginx-vhost:/etc/nginx/vhost.d"
      - "nginx-html:/usr/share/nginx/html"
      - "nginx-certs:/etc/nginx/certs:ro"
      - "/home/${MUD_HOST_USER}/config/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "nginx-certs:/etc/nginx/certs:rw"
      - "nginx-conf:/etc/nginx/conf.d"
      - "nginx-vhost:/etc/nginx/vhost.d"
      - "nginx-html:/usr/share/nginx/html"
      - "/home/${MUD_HOST_USER}/config/proxy.conf:/etc/nginx/proxy.conf"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - NGINX_PROXY_CONTAINER=nginx

  mud-proxy:
    restart: always
    image: mud-proxy
    build: ./
    container_name: mud-proxy
    environment:
      - VIRTUAL_HOST=${MUD_HOST}
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=${MUD_HOST}
      - LETSENCRYPT_EMAIL=admin@vault-thirteen.net


volumes:
  nginx-conf:
  nginx-vhost:
  nginx-html:
  nginx-certs:


